### ISSUE TITLE
Images are not served: 404 errors

### ISSUE THREAD

**Issue by kirill-konshin** [twopluszero/next-images#1]
I have following `next.config.js`:

```js
const withCss = require('@zeit/next-css');
const withImages = require('next-images');
module.exports = withCss(withImages({}));
```

And this is the component:

```js
import React from "react";
import Btn from "./Btn";
import Link from 'next/link';
import PNG from '../static/js.png';
import './Nav.css';

export default () => (
    <nav>
        <img src={PNG} className="logo" alt="Logo"/>
        <Link href="/" passHref><Btn>Index</Btn></Link>
        <Link href="/second" passHref><Btn>Second</Btn></Link>
    </nav>
);
```

Here is what I get:

![image](https://user-images.githubusercontent.com/1530410/36874792-1e4e3cac-1d62-11e8-9535-dc3049776cd3.png)
![image](https://user-images.githubusercontent.com/1530410/36874809-2b5c04d8-1d62-11e8-8d8d-f8088a8ae22c.png)

**Comment by realalexhomer** [comment]
I had this issue it turned out the the limit was too low:
https://github.com/arefaslani/next-images/blob/master/index.js#L16

I fixed it by just adding this rule to the config manually like:

    config.module.rules.push({ // separate rule for svg so we can have no limit
      test: /\.svg$/,
      use: [
        {
          loader: "url-loader",
          options: {
            fallback: "file-loader",
            publicPath: "/_next/",
            outputPath: "static/images/",
            name: "[name]-[hash].[ext]"
          }
        }
      ]
    });

**Comment by arefaslani** [comment]
@realalexhomer The limit is for creating base64 string from images under 8KBytes and insert image links for files more than 8Kbytes.

**Comment by arefaslani** [comment]
@kirill-konshin It was a problem in my webpack config. I've corrected the public path. A new version (0.9.2) is available that solved this issue.

**Comment by kirill-konshin** [comment]
Confirmed, it works.
