### ISSUE TITLE
Breaks with native css/sass/scss in Next.js 9.3+

### ISSUE THREAD

**Issue by tomdohnal** [twopluszero/next-images#31]
Next.js now imports images from css/sass/scss file by itself and we use `next-images` package together with it, it breaks the native image import in css/sass/scss functionality. 

As suggested in [this issue](https://github.com/zeit/next.js/issues/11164#issuecomment-602005679), the solution is to check the `issuer` in the `webpack` rule specification.

I can create a PR with the fix if you're interested.

**Comment by arefaslani** [comment]
Thanks @tomdohnal  for reporting this issue. I'll fix that today and will release a new patch for that.

**Comment by stegano** [comment]
Hope this issue will be resolved quickly

**Comment by arefaslani** [comment]
@tomdohnal @stegano This issue is fixed now. I'm really sorry, I had two projects to work on and it took me some time to come back to this repo and fix this issue.

**Comment by stegano** [comment]
Thanks for fixing this issue 👍  It works!

**Comment by tomdohnal** [comment]
> @tomdohnal @stegano This issue is fixed now. I'm really sorry, I had two projects to work on and it took me some time to come back to this repo and fix this issue.

No worries at all :) Thank you for the fix :)
