### ISSUE TITLE
Error: Module [the imported image] not found

### ISSUE THREAD

**Issue by quadsurf** [twopluszero/next-images#38]
I'm on NextJs 9.3.4 so I'm not using /static  nor  /public/static

steps to reproduce...
- i place image in /public sub-dir
- i call it using your import and API from within my  /pages  jsx files, as per docs
- i reboot the local server after adding image to /pages jsx files
- it fails to compile, with this exact error:

`Failed to compile`
`./pages/index.jsx`
`Module not found: Can't resolve './test-image.jpg' in '/Users/home/projects/next-apps/project1/src/pages'`

This could be the problem... if you look at the path above, it's resolving to the /pages sub-dir instead of the /public folder.

DO I NEED WEBPACK LOADERS??? Your docs did not say I needed it.

**Comment by agustif** [comment]
do you add to next.config.js

withImages({your config})

?
