### ISSUE TITLE
How to import CDN delivered images?

### ISSUE THREAD

**Issue by abhijit-hota** [twopluszero/next-images#45]
This is what my current `next.config.js` looks like. 
```javascript
const withImages = require('next-images')
module.exports = withImages({
  assetPrefix: 'https://cdn.jsdelivr.net/npm/simple-icons@v3/icons',
  webpack(config, options) {
    return config
  }
});
```
As mentioned, I'm using the `assetPrefix` option. 

But how do I import it in different pages and components?
I've tried with `src={require(`/css3.svg`)}`  but it doesn't work.

**Comment by arefaslani** [comment]
Will get fixed after merging this PR:
https://github.com/twopluszero/next-images/pull/44
