### ISSUE TITLE
Please add a license file and specify the copyright holder

### ISSUE THREAD

**Issue by kmacdonaO** [twopluszero/next-images#51]
The package.json indicates MIT License which is good but it's also a good practice to include a LICENSE or license file in your repo and this file would also have a line to specify who is the copyright holder.

Some company's need to see those copyrights to allow their employees to use open source packages...

**Comment by arefaslani** [comment]
@kmacdonaO Good point. Will add it. Thanks for reporting, because I also work for a licensing company ATM :D

**Comment by kmacdonaO** [comment]
thanks!

**Comment by arefaslani** [comment]
@kmacdonaO  I've just added it. You'll see it also in the package in the next release. Hopefully this weekend.
