### ISSUE TITLE
Regex not compatible IOS / Safari

### ISSUE THREAD

**Issue by GautheyValentin** [twopluszero/next-images#55]
Hello,

`issuer: /\.\w+(?<!(s?c|sa)ss)$/i,`

Create JS crash on Safari / IOS

To tempory fix, i use @1.3.0

If you have a other solution

**Comment by arefaslani** [comment]
@GautheyValentin Can I ask which versions of Safari are you using?

**Comment by GautheyValentin** [comment]
@arefaslani Hello 14.0 on macOS
You want i provide some screen with error ?

**Comment by arefaslani** [comment]
@GautheyValentin Yeah that'd be also nice 👍

**Comment by GautheyValentin** [comment]
@arefaslani   ![Capture d’écran 2020-10-20 à 08 09 51](https://user-images.githubusercontent.com/18257114/96547207-fbe92400-12ab-11eb-90a4-e457d176b614.png)

**Comment by arefaslani** [comment]
Have you been successful in solving this issue by now? Sorry, I just came back to check the issues. Seems like I need to change the regex to make it also compatible with the browsers you mentioned.

**Comment by GautheyValentin** [comment]
Hi, 

I just downgraded to `1.3.0` because it was an old regex and i didn't fixe this issue.

But maybe is my fault, what is your tsconfig ?

**Comment by arefaslani** [comment]
> Hi,
> 
> I just downgraded to `1.3.0` because it was an old regex and i didn't fixe this issue.
> 
> But maybe is my fault, what is your tsconfig ?

Actually, I don't work with Typescript, but I'll definitely try to see what's wrong...

**Comment by arefaslani** [comment]
@GautheyValentin Have you been successful in solving this problem?

**Comment by GautheyValentin** [comment]
No :(

**Comment by message** [comment]
Why this script is included in `_app.js`? It's a webpack script that should be executed in **build phase only.** You should require `next-images` from `next.config.js`.

**Comment by GautheyValentin** [comment]
It is already only in next.config.js 
```js
const widthImages = require("next-images");
const { nextI18NextRewrites } = require("next-i18next/rewrites");

const localeSubpaths = {
  fr: "fr",
  nl: "nl",
};

module.exports = {
  default: widthImages({
    webpackDevMiddleware: (config) => {
      config.watchOptions = {
        aggregateTimeout: 200,
        poll: 1000,
      };
      return config;
    },
    rewrites: async () => nextI18NextRewrites(localeSubpaths),
  }),
  localeSubpaths,
  env: {
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
  },
};
```

**Comment by alexthewilde** [comment]
Same here. `next-images` is required from within `next.config.js`, but its code is added to the app bundle.

**Comment by lvancraen** [comment]
When wrapping the regex `/\.\w+(?<!(s?c|sa)ss)$/i` with RegExp as such `new RegExp('\.\w+(?<!(s?c|sa)ss)$', 'i')` the error is resolved in Safari.
