### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by vincentpham13** [twopluszero/next-images#59]
Which folder did you mean to put the images?
I created an `images` folder inside the `public` folder but still got the error.
As your guide, the image should be located in the same directory of the code file, that's so weird.

**Comment by arefaslani** [comment]
Hey @vincentpham13. Sorry for the late response. The image could be anywhere, but I prefer to put it alongside the component file. As you see in this example:
```javascript
export default () => <div>
  <img src={require('./my-image.jpg')} />
</div>
```
the relative path is showing that the image is alongside the component itself. So to make it more clear, suppose that the component in the previous example is in this path: `/components/MyAwesomeComponent/index.js`, then the image file is here `/components/MyAwesomeComponent/my-image.jpg`.
