### ISSUE TITLE
creating multiple images with different sizes

### ISSUE THREAD

**Issue by wenzf** [twopluszero/next-images#6]
Is it possible to to set the webpack configurations so that multiple images with different sizes are created from one initial image. This would help to deliver the right sized image depending on screen sizes / resolutions. 
If it's possible to do this within next-images, I would be happy if you could give me some hints how to implement this.
Thanks a lot!

**Comment by arefaslani** [comment]
This could be done with something like [responsive-loader](https://github.com/herrstucki/responsive-loader). But maybe working with remote images become a problem. For now, you can use this loader to do what you want. I will check how to do that when I have more time.

**Comment by arefaslani** [comment]
I will close this issue. But you can reopen it if you think it should not be closed.
