### ISSUE TITLE
Could tags be pushed to GitHub?

### ISSUE THREAD

**Issue by jorrit** [twopluszero/next-images#66]
I would like to ask if version tags can be pushed for every release, as this project maintains no changelog file or GitHub releases. Having no git tags per version makes it hard to manually check the differences between releases.

If `npm version` is used to update the NPM version, a git tag should also be created. This tag can be pushed with `git push --tags`.

Thanks in advance!

**Comment by arefaslani** [comment]
@jorrit Good point. I pushed the tags and I think adding changelog would be fine. Thanks for the hint 👍

**Comment by jorrit** [comment]
Thanks!
