### ISSUE TITLE
Does next-images overwrite next/image?

### ISSUE THREAD

**Issue by PudparK** [twopluszero/next-images#68]
When I installed next-images next/image started to give a "Module not found" error. I looked [here](https://github.com/twopluszero/next-images#with-nextimage) and thought this might be my answer, but came up short.

Update: For some reason next/image isn't in my next install. Weird. Not a next-images issue. sorry.

**Comment by PudparK** [comment]
I'm starting to think next-images isn't the problem.

**Comment by shivamCode0** [comment]
If it is not an next-images issue, please close this pull request.
