### ISSUE TITLE
Can I use/tweak this plugin to also load images from scss files?

### ISSUE THREAD

**Issue by AmrAbdulrahman** [twopluszero/next-images#7]
The plugin perfectly works for requiring/importing images in ReactComponents
I just need it to work also for images in the styling files as following

```
.class {
  background-image: url('/images/hero/home.jpg');
}
```

Can this plugin be extended to handle this scenario as well?

**Comment by arefaslani** [comment]
AFAIK no. Because it uses JavaScript require to load images and only work in JavaScript files. Please let me know if you had any solution.
