### ISSUE TITLE
v1.8.3 has broken some image imports

### ISSUE THREAD

**Issue by marcjlyoung** [twopluszero/next-images#81]
Not to sure what happened but reverting to 1.8.2 without ^ solves the issue :) 

`./src/images/buttons/searchButton.svg
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <?xml version="1.0" encoding="utf-8"?>
| 
| <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
`

**Comment by marcjlyoung** [comment]
# How to fix the last commit

Why its broken: 

Seems the regex is not escaped correctly using new RegExp

![image](https://user-images.githubusercontent.com/33526616/143480337-8de636c7-ccfd-4793-80d2-94f4ebd058ae.png)

Solution: 
`new RegExp('\\.\\w+(?<!(s?c|sa)ss)$', 'i')`


# Temp solution

Adjust package.json to 1.8.2 without caret (^)

**Comment by arefaslani** [comment]
@marcjlyoung Could you help me with creating a PR?

**Comment by marcjlyoung** [comment]
> @marcjlyoung Could you help me with creating a PR?

Unfortunately I won't be able to assist right now, I quickly posted the solution so you could test it.  I'm away from my rig

**Comment by arefaslani** [comment]
@marcjlyoung Just added the fix and published a new version. Thanks for the help 👍
Do you think this change is in conflict with [this PR](https://github.com/twopluszero/next-images/pull/79)?
CC @lvancraen

**Comment by marcjlyoung** [comment]
No don't think there is a conflict, I just fixed the new regex param so that it created the same output as was previously there in v1.8.2, since it's still using the new regex function safari should be okay 👍
