### ISSUE TITLE
I see this error       TypeError: unsupported file type: undefined (file: undefined), after 11 -> 12 migration, can you help me?

### ISSUE THREAD

**Issue by mxomxo77mxo** [twopluszero/next-images#83]
![image](https://user-images.githubusercontent.com/62426263/150132783-7f9ac83e-44c3-476b-bb75-b4e4e4f527ff.png)

**Comment by beinoriusju** [comment]
How did you solve this?

**Comment by fcolacilli** [comment]
This worked for me:

In `next.config.js`:
```
const withImages = require("next-images");

module.exports = withImages({
  images: {
    disableStaticImages: true,
  },
});
```

And then, in the images I had with `src={StaticImage.src}`, I changed them to `src={StaticImage}`.

Then, I also had a vscode warning about static images types, which I solved with [this](https://github.com/parcel-bundler/parcel/issues/1445#issuecomment-392339363).
